### ISSUE TITLE
CF, "Adventure" model: "price" field data type wrong

### ISSUE THREAD

**Issue by stefangrimm** [adobe/aem-guides-wknd-shared#20]
### Expected Behaviour

The "price" field is defined as [a number/"Fraction" type in the model](https://github.com/adobe/aem-guides-wknd-shared/blob/b9f74e896883308e46655e97b07be590b1737c24/ui.content/src/main/content/jcr_root/conf/wknd-shared/settings/dam/cfm/models/adventure/.content.xml#L254). Therefore, its content should be stored as a JCR double value in the repository.

### Actual Behaviour

The value of a "price" field is stored as a JCR string in the repository. See for example [the Beervana fragment](https://github.com/adobe/aem-guides-wknd-shared/blob/462411b6d6225894e78bc470ac0ff1a7ef920de5/ui.content/src/main/content/jcr_root/content/dam/wknd-shared/en/adventures/beervana-portland/beervana-in-portland/.content.xml#L61).

Other fields != string may be affected as well.

### Reproduce Scenario (including but not limited to)

The problem will lead to invalid results with GraphQL queries after AEM CS 2023.02, where "hybrid filtering" is available.

#### Steps to Reproduce

GraphQL query

```graphql
query test {
  adventureList(   
    filter: {
      _logOp: OR,
      price: {_logOp: OR, _expressions: [{value: 200, _operator: LOWER_EQUAL}, {value: null}]},
      title: {_expressions: [{value: "Beer", _operator: CONTAINS}]}
    }
  ) {
    items {
      title
      price
    }
  }
}
```

will _not_ include `/content/dam/wknd-shared/en/adventures/gastronomic-marais-tour/gastronomic-marais-tour` in AEM >= 2023.02, despite the price being below 200, because the underlying JCR query will use a string instead of a numeric comparison.

#### Platform and Version

n/a

#### Sample Code that illustrates the problem

see "steps to reproduce"

#### Logs taken while reproducing problem

n/a

**Comment by SachinMali** [comment]
@stefangrimm Thanks and make sense, we will definitely try to address it provided the depending [WKND Headless (GraphQL) example application](https://github.com/adobe/aem-guides-wknd-graphql#examples-applications) won't have an impact. 

A quick analysis shows it should not matter as we are using the Util method to format the price

`{new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(price)}`

Also, your PR is welcome, just please cross-verify by running the [React App - WKND Adventures](https://github.com/adobe/aem-guides-wknd-graphql/tree/main/react-app#react-app---wknd-adventures) example

**Comment by stefangrimm** [comment]
@SachinMali To clarify, this is a bug in the content. Probably the field was initially defined as a "Single Line Text" in the model, but has been converted to a "Numeric" field later - which doesn't adjust the content in existing content fragments.

Note that the GraphQL output (which AFAIU is what the Headless example app is using) will not be affected at all, as AEM code was (and is still) converting repository data to the correct GraphQL type (in this case: from string to int) before the data is finally passed over to the underlying GraphQL library.

The change is only required to prevent regressions for a recent improvement in the GraphQL execution (= backend) layer, which introduces JCR-based filtering and therefore relies on the correct data type at the content layer: Strings are compared differently than numbers on the JCR layer, and JCR doesn't know about models, etc. and therefore must rely on the correct JCR data type.

Hope this makes sense.

**Comment by SachinMali** [comment]
@stefangrimm Thanks for the details and we made verified there is no regression on [AEM Guides WKND - GraphQL](https://github.com/adobe/aem-guides-wknd-graphql#aem-guides-wknd---graphql) and ready to close it.
